"""Receiver default configuration."""

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent

CHINESE_FONT_FAMILY = "SimHei"
LATIN_FONT_FAMILY = "Times New Roman"
UI_FONT_FAMILY = '"Times New Roman", SimHei, "Microsoft YaHei", serif'

LISTEN_HOST = "127.0.0.1"
LISTEN_PORT = 9000

SOCKET_TIMEOUT_SEC = 0.5
MAX_DATAGRAM_BYTES = 2048
SOCKET_RCVBUF_BYTES = 4 * 1024 * 1024

EXPECTED_TOTAL_SAMPLES = 393568
EXPECTED_CHUNK_COUNT = 2249
EXPECTED_CHANNELS = (0, 1)
CONSTELLATION_MAX_POINTS = 6000
EXPECTED_IMAGE_FRAME_BYTES = 12297
EXPECTED_IMAGE_BITS = EXPECTED_IMAGE_FRAME_BYTES * 8
REFERENCE_IMAGE_PATH = BASE_DIR.parent / "Transmitter" / "raw_pic_64.png"

PROGRESS_CHUNK_STEP = 100
PROGRESS_PERCENT_STEP = 5
IDLE_DIAGNOSTIC_SEC = 2.0

SAVE_COMPLETED_FRAMES = True
CAPTURE_DIR = BASE_DIR / "captures"

SAMPLES_PER_SYMBOL = 8
RRC_BETA = 0.35
RRC_SPAN = 8
