"""Receiver default configuration."""

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
RUNTIME_DIR = BASE_DIR / "runtime"

CHINESE_FONT_FAMILY = "SimHei"
LATIN_FONT_FAMILY = "Times New Roman"
MIXED_FONT_FAMILY = ("Times New Roman", "SimHei", "Microsoft YaHei")
UI_FONT_FAMILY = '"Times New Roman", "SimHei", "Microsoft YaHei", serif'

LISTEN_HOST = "0.0.0.0"
LISTEN_PORT = 9000
REFERENCE_DIR = RUNTIME_DIR / "reference"
REFERENCE_IMAGE_PATH = REFERENCE_DIR / "tx_reference.png"
MAX_REFERENCE_IMAGE_BYTES = 2 * 1024 * 1024
TX_PLOT_DIR = RUNTIME_DIR / "tx_plots"
MAX_TX_PLOTS_BYTES = 20 * 1024 * 1024

SOCKET_TIMEOUT_SEC = 0.5
MAX_DATAGRAM_BYTES = 2048
SOCKET_RCVBUF_BYTES = 4 * 1024 * 1024

EXPECTED_TOTAL_SAMPLES = 393568
EXPECTED_CHUNK_COUNT = 2249
EXPECTED_CHANNELS = (0, 1)
CONSTELLATION_MAX_POINTS = 6000
EXPECTED_IMAGE_FRAME_BYTES = 12297
EXPECTED_IMAGE_BITS = EXPECTED_IMAGE_FRAME_BYTES * 8

PROGRESS_CHUNK_STEP = 100
PROGRESS_PERCENT_STEP = 5
IDLE_DIAGNOSTIC_SEC = 2.0
INCOMPLETE_FRAME_ANALYSIS_TIMEOUT_SEC = 5.0
INCOMPLETE_FRAME_MIN_COMPLETION_RATIO = 0.95

SAVE_COMPLETED_FRAMES = True
CAPTURE_DIR = RUNTIME_DIR / "captures"
EXPORT_DIR = RUNTIME_DIR / "exports"
REPORT_DIR = RUNTIME_DIR / "reports"

SAMPLES_PER_SYMBOL = 8
RRC_BETA = 0.35
RRC_SPAN = 8
