"""Transmitter default configuration."""

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
IMAGE_PATH = BASE_DIR / "raw_pic_64.png"
WEB_DIR = BASE_DIR / "web"

EXPECTED_IMAGE_WIDTH = 64
EXPECTED_IMAGE_HEIGHT = 64
IMAGE_CHANNELS = 3

IMAGE_MAGIC = b"IMG0"

TARGET_HOST = "127.0.0.1"
TARGET_PORT = 9000

WEB_HOST = "0.0.0.0"
WEB_PORT = 8000

SNR_DB = 20.0
PHASE_DEG = 0.0
SNR_MIN_DB = -3.0
SNR_MAX_DB = 30.0
PHASE_MIN_DEG = -90.0
PHASE_MAX_DEG = 90.0

SAMPLES_PER_SYMBOL = 8
RRC_BETA = 0.35
RRC_SPAN = 8

RANDOM_SEED = 20260615

GENERATED_DIR = WEB_DIR / "static" / "generated"

PLOT_CHANNEL = "QDPSK"
EYE_TRACES = 120
EYE_SPAN_SYMBOLS = 2
CONSTELLATION_MAX_POINTS = 6000
PSD_NFFT = 4096
SAMPLE_RATE_HZ = 1.0

UDP_FRAGMENT_PAYLOAD_BYTES = 1400
UDP_INTER_PACKET_DELAY_SEC = 0.0
